addSbtPlugin("com.eed3si9n"     % "sbt-assembly"         % "0.14.3")
addSbtPlugin("org.scoverage"    % "sbt-scoverage"        % "1.4.0")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"        % "0.6.1")
addSbtPlugin("com.gilt"         % "sbt-dependency-graph-sugar" % "0.8.2")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.0")
addSbtPlugin("com.tapad"        % "sbt-docker-compose"     % "1.0.22")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.1")
